services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./storage:/app/storage  # ActiveStorageのファイルを永続化するための設定
    environment:
      RAILS_ENV: production
      DATABASE_HOST: db
      DATABASE_USERNAME: myapp_user
      DATABASE_PASSWORD: myapp_password
      DATABASE_NAME: myapp_db
      SECRET_KEY_BASE: YOUR_SECRET_KEY_BASE

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - web
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - webnet

networks:
  webnet:

volumes:
  mysql_data:
  storage:
