default: &default
  adapter: mysql2  # PostgreSQLからMySQLに変更
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>  # MySQL用の環境変数に合わせる
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 3306  # MySQLのポート

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

